In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
#y=mx+c where m = 3.5 and c= 4

In [4]:
m=3.5
c=4

In [5]:
x=np.random.randn(100)

In [6]:
x

array([ 0.59073468, -0.157636  ,  0.02492154, -0.10127367,  0.22681681,
       -0.85794234,  0.40452302, -0.60406022,  0.9593183 ,  0.32383488,
        1.25308972,  0.63665235,  0.82326875,  1.11301359,  0.31262807,
        0.06618342, -0.18314095,  0.02863167, -0.1893706 ,  0.64898492,
        0.61501069,  0.69233839,  0.46960112, -0.10502017, -1.50005256,
       -1.01718667,  0.27265733,  0.20901189, -0.03214121, -1.45768332,
        1.48657094,  0.57737232, -0.9434215 , -1.07102772, -0.80706327,
       -1.06288483,  0.514875  ,  0.24942934, -0.27124469,  2.20890371,
       -0.67296435, -1.07386108, -0.76216311, -0.11964351, -0.07234647,
       -0.49537696, -0.55954166,  0.75356613,  0.69568527,  0.87355521,
       -0.02391485, -0.79729317, -0.12227194,  0.33787837,  0.54617434,
       -1.60822207,  0.23573367, -0.7752347 ,  1.56264994, -0.22644462,
        0.49636685,  0.08419113, -1.8214926 ,  0.59064995,  0.61575379,
       -0.22851272, -1.37842817, -1.0541221 ,  0.93065336,  0.45

In [7]:
y=3.5*x+4

In [8]:
y

array([ 6.06757137,  3.44827401,  4.0872254 ,  3.64554214,  4.79385883,
        0.9972018 ,  5.41583058,  1.88578921,  7.35761406,  5.13342207,
        8.38581403,  6.22828324,  6.88144063,  7.89554757,  5.09419826,
        4.23164196,  3.35900666,  4.10021084,  3.33720291,  6.27144724,
        6.15253742,  6.42318436,  5.64360393,  3.6324294 , -1.25018394,
        0.43984664,  4.95430066,  4.73154161,  3.88750578, -1.1018916 ,
        9.20299828,  6.02080311,  0.69802476,  0.25140299,  1.17527857,
        0.2799031 ,  5.8020625 ,  4.8730027 ,  3.0506436 , 11.73116297,
        1.64462478,  0.24148622,  1.33242912,  3.58124772,  3.74678736,
        2.26618064,  2.04160418,  6.63748146,  6.43489845,  7.05744324,
        3.91629801,  1.2094739 ,  3.5720482 ,  5.18257431,  5.91161018,
       -1.62877725,  4.82506783,  1.28667853,  9.46927478,  3.20744382,
        5.73728397,  4.29466894, -2.37522409,  6.06727483,  6.15513827,
        3.2002055 , -0.82449861,  0.31057264,  7.25728677,  5.59

In [9]:
error= np.random.normal(loc=0,scale=0.6,size=100)

In [10]:
error

array([ 0.32052738,  0.27477441,  0.5873269 ,  0.57030857,  0.01793201,
       -1.00137345, -0.20635715, -0.5558513 ,  0.58989372,  1.65469512,
       -0.69170437, -0.17526669,  0.02366948, -0.68354977,  0.05740299,
        0.10625941,  0.25485479, -0.60113975,  1.52686386,  0.37528541,
       -0.21777623, -0.0542687 , -1.1932831 ,  0.39722277, -1.00163904,
       -0.22729925, -0.25913048,  0.47775641, -0.40856918,  0.77167427,
        0.74120944, -0.83090062,  1.08256011, -1.73660792, -0.47868167,
        0.25318146,  0.62797411,  0.3147974 ,  0.37937687,  0.84715269,
        0.54794235, -0.58408996, -0.31916835,  1.08203387, -0.54539384,
       -0.16644799,  0.53759844, -0.24088354, -0.22156979,  0.53303374,
        0.39339817,  0.27179255, -0.41992339,  0.22672227, -0.02187361,
        0.01113584,  0.34141252, -0.31996192, -1.0610041 ,  0.18444576,
        0.06141843,  0.39365271,  0.3082283 , -0.10916347, -0.87355067,
        1.39450174,  0.07381215,  0.77915996,  0.8522486 ,  0.27

In [11]:
y=y+error

In [12]:
y

array([ 6.38809876e+00,  3.72304842e+00,  4.67455230e+00,  4.21585071e+00,
        4.81179083e+00, -4.17165099e-03,  5.20947343e+00,  1.32993791e+00,
        7.94750778e+00,  6.78811719e+00,  7.69410966e+00,  6.05301655e+00,
        6.90511012e+00,  7.21199780e+00,  5.15160125e+00,  4.33790137e+00,
        3.61386146e+00,  3.49907109e+00,  4.86406677e+00,  6.64673265e+00,
        5.93476119e+00,  6.36891566e+00,  4.45032083e+00,  4.02965217e+00,
       -2.25182298e+00,  2.12547391e-01,  4.69517018e+00,  5.20929803e+00,
        3.47893660e+00, -3.30217333e-01,  9.94420772e+00,  5.18990249e+00,
        1.78058487e+00, -1.48520493e+00,  6.96596905e-01,  5.33084559e-01,
        6.43003660e+00,  5.18780010e+00,  3.43002047e+00,  1.25783157e+01,
        2.19256713e+00, -3.42603740e-01,  1.01326077e+00,  4.66328159e+00,
        3.20139352e+00,  2.09973265e+00,  2.57920262e+00,  6.39659793e+00,
        6.21332866e+00,  7.59047698e+00,  4.30969619e+00,  1.48126645e+00,
        3.15212481e+00,  

In [13]:
m1=10
c1=7

In [14]:
epoch=100
lr=0.01

In [17]:
for i in range(5000):
    loss=((y-x*m1-c1)*(y-m1*x-c1)).sum()
    loss=loss/100
    dm=(-2*x*(y-(m1*x+c1))).mean()
    dc=(-2*(y-(m1*x+c1))).mean()
    m1=m1-lr*dm
    c1=c1-lr*dc
    print(m1,c1)
    print(f"Loss is {loss}")

3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Loss is 0.3938083650569238
3.5391975534438207 4.027747019967981
Los

In [18]:
print((y-(m1*x+c)).mean())

0.02774701996795928
